/* Unique private-auction lines for /tv — one per slide until exhausted, then reshuffled */
window.TV_CAPTIONS = [
  "Private auction · thali on · nothing hidden from the room.",
  "Look carefully. This is what you are negotiating.",
  "Soft eyes. Shared nights. Still hungry for the highest claim.",
  "Mangalsutra wife energy — presented for serious interest only.",
  "Before the gold… and after she was already ruined properly.",
  "Chennai wife. Village face. Hotel body. One product.",
  "He owns the arrangement. She wears the gold. You bid the night.",
  "Don't rush the reel — shy in stills, open when claimed.",
  "18+ · Closed room · Invitation only · Serious bids only.",
  "Three faces of her at once — choose the night you want.",
  "Viji from Kovilpatti — soft smile, shared reputation.",
  "Bala sets the price floor. The room decides who rises.",
  "Thali bright. Knees soft. Who claims her next?",
  "This is not girlfriend energy. This is wife-for-the-night energy.",
  "Dusky skin under gold — inspect before you speak numbers.",
  "She keeps the mangalsutra on when strangers finish inside her.",
  "First look free. The night is not.",
  "Chennai couple swap product — live on your wall.",
  "Her eyes say shy. Her body already knows the script.",
  "If you are only looking, step back. If you are bidding, lean in.",
  "Silk, sweat, and a husband who likes to watch.",
  "Auction rule one: respect the gold. Ruin everything else.",
  "Vijayalakshmi — twenty-five, trained, still blushing on camera.",
  "The softest face in the room. The wettest deal on the table.",
  "Hotel sheets not included. Her moans come free with the claim.",
  "Bala Viji brand — soft Tamil wife, filthy Chennai nights.",
  "You are not buying romance. You are buying access.",
  "Watch the thali swing. That is the product marker.",
  "Village manners. City rates. Husband-approved sharing.",
  "She accepted the camera for money and clients — remember that.",
  "First tape energy: shy, paid, and opening anyway.",
  "Every frame is a sample. The night is the contract.",
  "Raise your interest before someone else locks the date.",
  "Anklets sing when she walks — and when she gets fucked.",
  "Soft hands. Firm breasts. A hole that grips after years of use.",
  "Couples and singles — know your slot before you speak.",
  "He will be in the room. That is not optional.",
  "Her brothers must never know. Your discretion is part of the bid.",
  "Mangalsutra slut wife — sacred look, shared use.",
  "Chennai heat, Kovilpatti face, auction silence — perfect mix.",
  "Look at her mouth. Imagine what it does when told.",
  "Red silk nights cost more. Soft PG looks cost different. Choose a lot.",
  "She cums in Tamil. Factor that into your appetite.",
  "Bala handles logistics. You handle stamina and cash clarity.",
  "No time-wasters. Hard cocks and clear numbers only.",
  "This smile sold rooms before. It can sell yours.",
  "Inspect the eyes — that is how she looks while taking cock.",
  "Shared wife presentation complete. Negotiation is open.",
  "Three portraits: morning soft, hotel wet, afterglow owned.",
  "If your pulse is calm, you are underbidding.",
  "Gold between her breasts is not decoration. It is branding.",
  "She was shy on her first recording. She is still soft. She is not closed.",
  "Bid like you want her remembering your name tomorrow.",
  "Tamil wife aesthetic for men who can afford the night.",
  "The reel is long so nobody claims they didn't see enough.",
  "Pause if you need. Prices get fixed in stillness.",
  "Her body history is written in these frames.",
  "From UPSC girl rumors to mangalsutra product — full arc on screen.",
  "Couple swap India energy with a face you will not forget.",
  "When she bites her lip, the room usually raises.",
  "Clean face. Filthy nights. That contrast is the premium.",
  "Bala is not leaving. You are joining a structure.",
  "Wife look for the photo. Whore rules after the door locks.",
  "Count her expressions — each one is a different way she opens.",
  "Chennai couple. Private auction. No public drama.",
  "She keeps eye contact when she is told to. Test that if you win.",
  "Soft thighs, trained obedience, market-ready hunger.",
  "This is Viji. Say it correctly when you claim her.",
  "Vijayalakshmi — full name for the contract, Viji for the bed.",
  "Look at the hands on her waist — sometimes his, sometimes not.",
  "Hotel window light loves her. So will the winner.",
  "Saree nights and naked mornings — both are on the menu of possibilities.",
  "If you wanted pure monogamy, you walked into the wrong reel.",
  "Shared, watched, returned wet to her husband — the loop.",
  "Her first video was for money and clients. This room is the harvest.",
  "Serious faces only. Smirking tourists leave soft.",
  "The gold stays on. Everything else is negotiable by package.",
  "She looks holy until the moan starts.",
  "Bala's pride is part of the show. Respect it.",
  "Dusky, lean, firm — built for long nights.",
  "Three-wide portraits so nobody misses a angle.",
  "Claim the night, not the Instagram fantasy alone.",
  "Soft voice. Filthy vocabulary when ordered.",
  "Chennai after dark starts with a number that makes sense to him.",
  "She will still blush. That is not fake. That is product quality.",
  "Watch her throat when she swallows nerves — and cock.",
  "Private auction liner: beauty first, terms second, use third.",
  "No brothers. No mothers. Only men who can keep a secret and a schedule.",
  "Her anklets will be the soundtrack of your win.",
  "Mangalsutra glint means the fantasy is locked in.",
  "You are bidding on access, not ownership of her life — know the difference.",
  "Bala owns the leash. You rent the night.",
  "Soft eyes that have already seen too much — and still invite more.",
  "The room that hesitates loses her to the room that doesn't.",
  "Tamil heat without the plastic porn face — that is the premium.",
  "Inspect posture: open knees sell themselves.",
  "She accepted ruin for money. Your bid continues that story.",
  "First-time camera fear still lives in her lashes — use it.",
  "Hotel carpet burns optional. Her obedience is not.",
  "Couples: bring your rules. She already has his.",
  "Singles: bring stamina. She is not a five-minute fantasy.",
  "Aftercare is his. Your job ends when you leave her dripping.",
  "Look at that mouth mid-moan freeze-frame — that is the product speaking.",
  "Chennai couple swap without the cheap club smell — private, deliberate.",
  "She is twenty-five. Trained. Still soft enough to make you cruel.",
  "Bid while the frame is soft. The hard night comes after.",
  "Her hair down means the night is already half won.",
  "Thali, kumkum, jasmine — costume for men who pay to desecrate.",
  "If you need alcohol to decide, you are not ready for her.",
  "Clear cash energy. Clear night energy. Clear who watches.",
  "Viji's silence in stills is temporary. She gets loud.",
  "The husband smile in frame is not accidental. It is policy.",
  "Shared wife Chennai edition — limited room, unlimited hunger.",
  "Every still is a receipt of what she already survived.",
  "You are not her first. Be good enough to be remembered.",
  "Soft lighting hides nothing important.",
  "When she looks down, she is performing purity. When she looks up, she is ready.",
  "Bala Viji standard: gold on, legs open, story sealed.",
  "Lot energy: face, body, obedience, discretion — four pillars.",
  "Do not lowball a face that already made other men rewrite plans.",
  "She was sold as innocent once. Now she sells as experienced soft.",
  "The reel keeps moving so greed stays warm.",
  "Pause on the eyes if you are about to speak a number.",
  "Her first sex tape bought the clients. Tonight buys you.",
  "Village girl myth. City wife reality. Auction present tense.",
  "Touch is later. Sight is now. Decide like a man who will follow through.",
  "Three portraits: choose which mood you want in the room with you.",
  "She keeps the gold on during doggy so you never forget the genre.",
  "Filthy Tamil whispers included. Translation optional.",
  "Chennai nights are long. Price them like it.",
  "If your friends are hard, your bid should be serious.",
  "This is presentation, not free porn. Act like bidders.",
  "Soft stomach, firm breasts, trained cunt — the inventory.",
  "She will say please when told. Confirm you like that.",
  "Bala's rules travel with her. Read the room.",
  "No public brand damage. Private ecstasy only.",
  "The smile that looks married is the smile that opens paid.",
  "Watch the hip tilt — that is experience, not accident.",
  "Kovilpatti softness, Chennai pricing logic.",
  "You wanted unique. She is unique. Pay like it.",
  "Still frames are free. Her hours are not.",
  "When the thali catches light, the fantasy closes on the winner.",
  "Husband-present sharing — the luxury tier of ruin.",
  "She is not confused. She is performing confusion for heat.",
  "Your number should match how long you stared.",
  "Private auction ethic: see all, then speak once clearly.",
  "Viji afterglow faces sell second nights. Plan ahead.",
  "She accepted money over shame. Respect the transaction.",
  "Hard cock is interest. Clear offer is respect.",
  "Mangalsutra wife lot — currently on screen, not yet claimed tonight.",
  "Bala will watch your hands on her. Smile if you can.",
  "Soft neck. Strong grip needed — she shakes when she cums.",
  "The camera made her famous in the wrong rooms. You are in one.",
  "Do not rush past a face that took years to ruin properly.",
  "Shared, wet, returned — the loop that funds the silk.",
  "If you want her shy, say so. If you want her filthy, say so louder.",
  "Auction liner: beauty is the hook; obedience is the close.",
  "Chennai couple power: he directs, she delivers, you pay the night.",
  "Her first recording fear still makes the eyes expensive.",
  "Look at the mouth open mid-breath — that is the money shot of personality.",
  "Gold chain, wet thighs, closed door — finish the equation.",
  "You are bidding against every man who already imagined this.",
  "Keep the room classy. Keep the night filthy.",
  "Vijayalakshmi full name for dignity. Viji for the bed moan.",
  "The stills do not blink. You should not either until you decide.",
  "Soft lighting, hard truth: she opens for the right claim.",
  "Bala Viji quality control: no weak offers, no loud fools.",
  "She will wear whatever the night requires. Start with the face.",
  "Three-wide so the whole couch can argue without pausing.",
  "If you came to browse, browse. If you came to buy time, speak.",
  "Her reputation is the product wrapping. Her body is the product.",
  "Tamil wife fantasy with receipts in every frame.",
  "The husband is not a problem. The husband is the feature.",
  "Night claim includes her trained line in Tamil — if you earn it.",
  "Do not negotiate like she is average. She is not.",
  "Soft eyes at the lens are soft eyes on your cock later — if you win.",
  "Auction pace is slow so cowards self-eliminate.",
  "She was paid to start. You pay to continue.",
  "Chennai heat signature: silk, gold, sweat, silence after.",
  "Inventory check: face yes, body yes, discretion yes, hunger yes.",
  "When she looks almost innocent, the premium is highest.",
  "Bala's hand in frame means the brand is present.",
  "You fix the price. She fixes her sari. Then it comes off.",
  "Private room only — this reel is the catalog, not the streets.",
  "Her moan is the closing argument. The still is the opening.",
  "If your mouth is dry, drink water. If your resolve is dry, leave.",
  "Shared wife Chennai standard applied in full.",
  "Viji will remember the man who claimed her gently and used her fully.",
  "The gold never leaves. Your restraint can.",
  "One product, many angles, one decision.",
  "Serious bidders watch the whole reel. Soft boys skip and lose.",
  "She opens for structure. Bring structure.",
  "Look. Want. Number. Door. That is the order.",
  "Mangalsutra light flare — trademark of the lot.",
  "Her first recording bought the market. Tonight you enter it.",
  "Dusky, soft, ruined on schedule — Chennai precision.",
  "If you need a second look, take it. That is why the timer is slow.",
  "Bala Viji auction ethics: clear, adult, no public fallout.",
  "She is the reason soft men become decisive.",
  "Claim energy only. Curiosity is free; the night is not.",
  "Watch the throat. Watch the eyes. Then watch your mouth when you bid.",
  "Tamil heat, English terms, closed-room enforcement.",
  "The product is wetter than the stills. Price accordingly.",
  "Husband-approved hunger — rare and expensive.",
  "You are not stealing a wife. You are booking a shared one.",
  "Final reminder in this block: thali on, story sealed, night sold to the ready.",
  "Viji is patient on screen. The market is not.",
  "Make the offer you will not regret when she undresses.",
  "Private auction complete presentation — decide like you mean to fuck.",
  "Soft frame. Hard night. Your move.",
  "This face closed deals before. Be the next line in her private ledger.",
  "Chennai couple. Shared wife. Open bids in the room only.",
  "She stays soft so you stay cruel enough to claim her properly.",
  "If you still have no number after this face, you were never bidding."
];
