#!/usr/bin/env python3
"""Rebuild tv/images-data.js + images.json from site + auction packs."""
from pathlib import Path
from PIL import Image
import json
import re

ROOT = Path(__file__).resolve().parents[1]
EXT = {".jpg", ".jpeg", ".png", ".webp", ".gif"}
DIRS = [
    ROOT / "assets" / "pictures",
    ROOT / "assets1" / "viji-auction",
    ROOT / "assets" / "videos",
]


def main():
    portraits, landscapes = [], []
    seen = set()
    for d in DIRS:
        if not d.exists():
            print("skip missing", d.relative_to(ROOT))
            continue
        for p in sorted(d.rglob("*")):
            if p.suffix.lower() not in EXT or not p.is_file():
                continue
            rel = p.relative_to(ROOT).as_posix()
            key = rel.lower()
            if key in seen:
                continue
            seen.add(key)
            try:
                w, h = Image.open(p).size
            except Exception as e:
                print("skip unreadable", rel, e)
                continue
            item = {"src": "/" + rel, "w": w, "h": h}
            if h >= w * 1.05:
                portraits.append(item)
            else:
                landscapes.append(item)

    data = {"portraits": portraits, "landscapes": landscapes}
    tv = ROOT / "tv"
    tv.mkdir(exist_ok=True)
    (tv / "images.json").write_text(json.dumps(data, indent=2))
    (tv / "images-data.js").write_text(
        "/* auto-generated by scripts/rebuild-tv-images.py */\n"
        "window.TV_IMAGES = "
        + json.dumps(data)
        + ";\n"
    )
    print(
        f"OK portraits={len(portraits)} landscapes={len(landscapes)} "
        f"total={len(portraits) + len(landscapes)}"
    )


if __name__ == "__main__":
    main()
